services:
  app:
    build: .
    init: true
    working_dir: /workspaces/sandbox-webcg
    entrypoint: /workspaces/sandbox-webcg/.devcontainer/entrypoint.sh
    command: sleep infinity
    environment:
      PNPM_HOME: /usr/local/share/pnpm
      PATH: /usr/local/share/pnpm:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
